// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `hello.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package perv.cmy.zerocice.hello.meta;

public abstract class Callback_MyService_hellow
        extends IceInternal.TwowayCallback implements Ice.TwowayCallbackArg1<String> {
    public final void __completed(Ice.AsyncResult __result) {
        MyServicePrxHelper.__hellow_completed(this, __result);
    }
}
