// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `book_store.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package perv.cmy.zerocice.book.meta;

public abstract class Callback_OnlineBook_bookTick
        extends IceInternal.TwowayCallback implements Ice.TwowayCallbackArg1<perv.cmy.zerocice.book.meta.Message> {
    public final void __completed(Ice.AsyncResult __result) {
        OnlineBookPrxHelper.__bookTick_completed(this, __result);
    }
}
