// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `book_store.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package perv.cmy.zerocice.book.meta;

public interface OnlineBook extends Ice.Object,
        _OnlineBookOperations, _OnlineBookOperationsNC {
    public static final String ice_staticId = "::meta::OnlineBook";

    public static final long serialVersionUID = 499327750L;
}
