// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `book_store.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package perv.cmy.zerocice.book.meta;

public final class OnlineBookHolder extends Ice.ObjectHolderBase<OnlineBook> {
    public OnlineBookHolder() {
    }

    public OnlineBookHolder(OnlineBook value) {
        this.value = value;
    }

    public void
    patch(Ice.Object v) {
        if (v == null || v instanceof OnlineBook) {
            value = (OnlineBook) v;
        } else {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type() {
        return _OnlineBookDisp.ice_staticId();
    }
}
